---
- hosts: demo
  tasks:
        - name: Mount filesystem
          mount:
                name: /mnt/data
                src: /dev/vg_sql/lv_data
                fstype: ext4
                state: mounted
