--- #Installing Packages over the child node
- hosts: demo
  user: root
  become: yes
  connection: ssh
  tasks:
        - name: Install Apache on the node
          action: yum name=httpd state=installed
          notify: restart httpd
        - name: Enable Apache on Reboot
          service: name=httpd enabled=yes
        - name: Install firewalld on the node
          action: yum name=firewalld state=installed
        - name: Install DB on the node
          action: yum name=mariadb-server state=installed
          notify: restart mariadb
        - name: Install PHP
          action: yum name=php state=installed
          notify: restart php
        - name: Install PHP-MYSQL
          action: yum name=php-mysql state=installed
          notify: restart php-mysql
  handlers:
          - name: restart httpd
            service: name=httpd state=started
          - name: restart mariadb
            service: name=mariadb-server state=started
          - name: restart php
            service: name=php state=started
          - name: restart php-mysql
            service: name=php-mysql state=started 
